# Generated by Django 4.0.3 on 2022-11-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
